# .streamlit/secrets.toml

# Authentication settings
BYPASS_AUTH = true  # Set to true to allow login without Firebase auth (for development)

# Firebase configuration
# These will be populated from environment secrets